Library/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from.views import MainIndex, BookDetailPage, PurchasePage, PaymentProcessPage, FeedbackReportPage, add_to_cart, CategoryBasedPage


app_name = 'Library'
urlpatterns = [
   path('', MainIndex.as_view(), name="main"),
   path('book/<pk>', BookDetailPage.as_view(), name="book_detail"),
   path('purchase_book/<book_id>', login_required(PurchasePage.as_view()), name='purchase'),
   path('purchase_book/payment_process/<address>/<shipment_method>/<payment_method>/<book_id>', login_required(PaymentProcessPage.as_view()), name='payment_process'),
   path('feedback-report/contact-us', FeedbackReportPage.as_view(), name='feedback_report'),
   path('book/add-to-cart/<book_id>', add_to_cart, name="add_to_cart"),
   path('category/<category_id>', CategoryBasedPage.as_view(), name="category_based")
]

Seller/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import AddProductPage, OpenSellerAccount, ProductImageUpload, SellerAccountPage, EditSellerAccountPage, EditProductPage, CustomerOrderPage, update_track

app_name = "Seller"
urlpatterns = [
   path('add-product/', login_required(AddProductPage.as_view()), name='add_product'),
   path('edit-product/<pk>', login_required(EditProductPage.as_view()), name='edit_product'),
   path('profile/open-seller-account', login_required(OpenSellerAccount.as_view()), name='open_seller_account'),
   path('product-image-upload/<book_id>', login_required(ProductImageUpload.as_view()), name='upload_image'),
   path('account/<seller_id>', login_required(SellerAccountPage.as_view()), name='account'),
   path('account/edit/<pk>', login_required(EditSellerAccountPage.as_view()), name='edit_seller_account'),
   path('customer_orders/', login_required(CustomerOrderPage.as_view()), name="customer_orders"),
   path('order/udpate_track/<order_id>', login_required(update_track), name="udpate_track"),
]

User/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import WelcomePage, SignUpPage, SignInPage, LogoutPage, ProfilePage, AboutAccountPage, PrivacySecurityPage, SetAddressPage, TransactionHistory, UserCartList

app_name = "User"
urlpatterns = [
   path('', WelcomePage.as_view(), name='welcome'),
   path('sign-up', SignUpPage.as_view(), name='sign_up'),
   path('sign-in', SignInPage.as_view(), name='sign_in'),
   path('user/logout', login_required(LogoutPage.as_view()), name='logout'),
   path('user/profile', login_required(ProfilePage.as_view()), name='profile'),
   path('user/profile/about-account', login_required(AboutAccountPage.as_view()), name='about_account'),
   path('user/profile/privacy-security', login_required(PrivacySecurityPage.as_view()), name='privacy_security'),
   path('user/profile/set-address', login_required(SetAddressPage.as_view()), name='set_address'),
   path('user/history/transaction', login_required(TransactionHistory.as_view()), name='transaction_history'),
   path('user/cart/list', login_required(UserCartList.as_view()), name='cart_list'),
]

Library/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.utils import timezone
from navigation.models import Category
from Seller.models import Seller

# Create your models here.
def minimum_price(value):
   if value > 0:
      return value
   else:
      return ValidationError('Please input price of more than $0')


class Book(models.Model):
   name           = models.CharField(max_length=255, unique=True)
   author         = models.CharField(max_length=150)
   category       = models.ForeignKey(Category, on_delete=models.CASCADE)
   desc           = models.TextField(blank=True)
   synopsis       = models.TextField(blank=True)
   publisher      = models.CharField(max_length=150)
   total_pages    = models.PositiveIntegerField()
   total_chapters = models.PositiveIntegerField()
   publish_year   = models.PositiveIntegerField()
   stock          = models.PositiveIntegerField()
   weight         = models.PositiveIntegerField()
   size           = models.CharField(max_length=100)
   serial_number  = models.CharField(max_length=13)
   price          = models.DecimalField(decimal_places=2, max_digits=10,validators=[minimum_price])
   created_at     = models.DateTimeField(auto_now_add=True)
   seller         = models.ForeignKey(Seller, on_delete=models.CASCADE, blank=True)
   book_activated = models.BooleanField(default=0)

   def __str__(self):
      return f"{self.name} | ${self.price}"


class BookPicture(models.Model):
   image         = models.ImageField(upload_to='book_picture/')
   book          = models.ForeignKey(Book, on_delete=models.CASCADE)
   is_main_image = models.BooleanField(default=False)

   def __str__(self):
      return f"Image for {self.book.name}"


class Transaction(models.Model):
   address         = models.CharField(max_length=150)
   payment_method  = models.CharField(max_length=100)
   shipment_method = models.CharField(max_length=100)
   book            = models.ForeignKey(Book, on_delete=models.CASCADE)
   user            = models.ForeignKey(User, on_delete=models.CASCADE)
   seller          = models.ForeignKey(Seller, on_delete=models.CASCADE)
   created_at      = models.DateTimeField(auto_now_add=True)
   arrival_status  = models.CharField(max_length=50, default="Waiting For Confirmations")
   arrive_date     = models.DateField(blank=True, null=True)
   # Waiting For Confirmations
   # Currently On Shipping
   # Book Arrived!

   
   def __str__(self):
      return f"{self.book.name} | {self.user.username} - {self.address}"

   def save(self, *args, **kwargs):
      if self.arrival_status == 'Book Arrived!':
         self.arrive_date = timezone.now()
      super(Transaction, self).save(*args, **kwargs)


class FeedbackReport(models.Model):
   name    = models.CharField(max_length=150)
   email   = models.EmailField()
   message = models.TextField()

   def __str__(self):
      return "Message from " + self.name


class BookRating(models.Model):
   user   = models.ForeignKey(User, on_delete=models.CASCADE)
   book   = models.ForeignKey(Book, on_delete=models.CASCADE)
   rating = models.FloatField()

   def __str__(self):
      return f"{self.rating} for {self.book.name} | by {self.user.username}"

Seller/models.py
from django.db import models
from PIL import Image
from User.models import User

# Create your models here.
class Seller(models.Model):
   user           = models.OneToOneField(User, primary_key=True, on_delete=models.CASCADE, related_name='seller_account')
   store_name     = models.CharField(max_length=100)
   phone_number   = models.CharField(max_length=12)
   desc           = models.TextField()
   image          = models.ImageField(upload_to='store_picture/', null=False)
   location       = models.CharField(max_length=150)
   created_at     = models.DateTimeField(auto_now_add=True)
   account_active = models.BooleanField(default=False)

   def __str__(self):
      return f"{self.store_name} From Account - {self.user.username}"
   
   def save(self, *args, **kwargs):
      super(Seller, self).save(*args, **kwargs)
      if self.image:
         image = Image.open(self.image.path)
         image.thumbnail((230, 230))
         image.save(self.image.path)

Seller/forms.py
from django import forms
from Library.models import Book, BookPicture
from Seller.models import Seller

class NewProductForm(forms.ModelForm):
   class Meta:
      model = Book
      exclude = ['created_at']
      widgets = {
         'name': forms.TextInput(attrs={'class': 'block w-full border border-slate-500 px-3 py-2 text-sm outline-none'}),
         'author': forms.TextInput(attrs={'class': 'block w-full border border-slate-500 px-3 py-2 text-sm outline-none'}),
         'category': forms.HiddenInput(),
         'desc': forms.Textarea(attrs={'class': 'block w-full border border-slate-500 px-3 py-2 text-sm outline-none resize-none'}),
         'synopsis': forms.Textarea(attrs={'class': 'block w-full border border-slate-500 px-3 py-2 text-sm outline-none resize-none'}),
         'publisher': forms.TextInput(attrs={'class': 'block w-full border border-slate-500 px-3 py-2 text-sm outline-none'}),
         'publish_year': forms.NumberInput(attrs={'class': 'block w-full border border-slate-500 px-3 py-2 text-sm outline-none'}),
         'stock': forms.NumberInput(attrs={'class': 'block w-full border border-slate-500 px-3 py-2 text-sm outline-none'}),
         'total_pages': forms.NumberInput(attrs={'class': 'block w-full border border-slate-500 px-3 py-2 text-sm outline-none'}),
         'total_chapters': forms.NumberInput(attrs={'class': 'block w-full border border-slate-500 px-3 py-2 text-sm outline-none'}),
         'weight': forms.NumberInput(attrs={'class': 'block w-full border border-slate-500 px-3 py-2 text-sm outline-none'}),
         'size': forms.HiddenInput(),
         'serial_number': forms.TextInput(attrs={'class': 'block w-full border border-slate-500 px-3 py-2 text-sm outline-none'}),
         'price': forms.TextInput(attrs={'class': 'coma-regexed block w-full border border-slate-500 px-3 py-2 text-sm outline-none'}),
      }

class SellerDataForm(forms.ModelForm):
   class Meta:
      model = Seller
      fields = ['store_name', 'phone_number','image', 'desc', 'location']
      widgets = {
         'store_name': forms.TextInput(attrs={
            'class': 'w-full bg-transparent border-b border-slate-500 pb-1 placeholder:text-neutral-400 outline-none',
            'placeholder': 'Input Your Store Name',
            'autocomplete': 'off'
         }),
         'phone_number': forms.TextInput(attrs={
            'class': 'block w-full border border-neutral-500 outline-none p-2 text-sm',
            'placeholder': 'enter a valid phone number'
         }),
         'desc': forms.Textarea(attrs={'class': 'w-full border border-neutral-500 rounded-sm p-3 outline-none resize-none'}),
         'image': forms.FileInput(attrs={'class': 'hidden'}),
         'location': forms.TextInput(attrs={
            'class': 'block w-full border border-neutral-500 outline-none p-2 text-sm',
            'placeholder': 'your location'
         })
      }

Seller/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.views.generic import CreateView, TemplateView, View, UpdateView
from django.utils import timezone
from Library.models import Transaction, Book, BookPicture
from .forms import NewProductForm, SellerDataForm
from .models import Seller

# Create your views here.
class AddProductPage(CreateView):
   template_name = 'seller/add_product.html'
   form_class = NewProductForm

   def post(self, request, *args, **kwargs):      
      form = NewProductForm(request.POST)
      if form.is_valid():
         form.save()

         seller_account = Seller.objects.get(user_id=request.user.id)
         if not seller_account.account_active:
            seller_account.account_active = True
            seller_account.save()

         messages.success(request, 'Your new product has been successfully uploaded into the database.')

         return redirect('Seller:upload_image', book_id=form.instance.id)
      return super().post(self, request)


class OpenSellerAccount(CreateView):
   template_name = 'seller/open_seller_account.html'
   model = Seller
   form_class = SellerDataForm

   def post(self, request, *args, **kwargs):
      form = SellerDataForm(request.POST, request.FILES)
      if form.is_valid():
         store_name   = form.cleaned_data['store_name']
         phone_number = form.cleaned_data['phone_number']
         image        = form.cleaned_data['image']
         desc         = form.cleaned_data['desc']
         location     = form.cleaned_data['location']

         new_seller_account = Seller(
            store_name   = store_name,
            phone_number = phone_number,
            image        = image,
            desc         = desc,
            location     = location,
            user         = request.user,
         )
         new_seller_account.save()

         messages.success(request, 'You have made your seller account. But before we publicize you account, please upload your first product.')

         return redirect('Seller:add_product')
      return super().post(self, request)


class ProductImageUpload(View):
   template_name = 'seller/product_image_form.html'

   def get(self, request, *args, **kwargs):
      book = Book.objects.get(id=kwargs['book_id'])
      return render(request, self.template_name, {
         'book_name': book.name
      })
   
   def post(self, request, *args, **kwargs):
      book = Book.objects.get(id=kwargs['book_id'])

      if len(request.FILES) > 0:
      
         current_images = BookPicture.objects.filter(book=book)
         for image in current_images:
            image.delete()
         
         for x in range(1, len(request.FILES) + 1):
            if x == 1:
               new_picture = BookPicture(image=request.FILES['image' + str(x)], book=book, is_main_image=1)
            else:
               new_picture = BookPicture(image=request.FILES['image' + str(x)], book=book)

            if book.book_activated == 0:
               book.book_activated = 1
               book.save()

            new_picture.save()

            messages.success(request, 'Congratulation!! Your product is successfully publisized. Time to wait for buyers.')
            return redirect('Library:book_detail', pk=book.id)


      messages.error(request, 'Please upload at least 1 image!!')
      return render(request, self.template_name, {
         'book_name': book.name
      })


class SellerAccountPage(TemplateView):
   template_name = 'seller/account.html'

   def get_context_data(self, **kwargs):
      page_context = super().get_context_data()
      seller = Seller.objects.get(pk=kwargs['seller_id'])
      page_context['seller'] = seller
      page_context['books'] = Book.objects.filter(book_activated=1, seller=seller).order_by('-id')
      return page_context


class EditSellerAccountPage(UpdateView):
   template_name = 'seller/open_seller_account.html'
   model = Seller
   form_class = SellerDataForm

   def get(self, request, *args, **kwargs):
      if kwargs['pk'] != request.user.id:
         return render(request, self.template_name, {
            'form': self.form_class(instance=Seller.objects.get(pk=request.user))
         })

      return redirect('Seller:edit_seller_account', seller_id=request.user.id)


   def get_success_url(self):
      messages.success(self.request, 'Your seller account has been updated!')
      return reverse("Seller:account", kwargs={'seller_id': self.request.user.id})



class EditProductPage(UpdateView):
   template_name = 'seller/add_product.html'
   model = Book
   form_class = NewProductForm

   def get_context_data(self, **kwargs):
      page_context = super().get_context_data()
      page_context['book_id'] = page_context['book'].id
      return page_context

   def form_valid(self, form):
      object_id = self.object.id
      return HttpResponseRedirect(self.get_success_url(object_id))

   def get_success_url(self, book_id):
      print(book_id)
      return reverse_lazy("Library:book_detail", kwargs={'pk': book_id})


class CustomerOrderPage(TemplateView):
   template_name = 'seller/customer_order.html'

   def get(self, request, *args, **kwargs):
      seller = Seller.objects.get(pk=request.user.id)
      
      return render(request, self.template_name, {
         'orders': Transaction.objects.filter(seller=seller, arrive_date=None).order_by('-id')
      })

def update_track(request, order_id):
   order_step = ["Waiting For Confirmations", "Currently On Shipping", "Book Arrived!"]
   order = Transaction.objects.get(pk=order_id)
   current_index = order_step.index(order.arrival_status)

   if current_index == 2:
      messages.success(request, 'Order already arrived!! No need to update it again!')
      return redirect('Seller:customer_orders')

   order.arrival_status = order_step[current_index + 1]
   if current_index == 1:
      order.arrive_date = timezone.now()

   order.save()

   messages.success(request, 'Order already updated!!')
   return redirect('Seller:customer_orders')

   

templates/seller/account.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}Your Seller Account {% endblock %}

{% block content %}
<main class="pt-16 md:pt-20 pb-16">
   <div class="w-full h-60 bg-red-200"></div>
   <section class="w-11/12 md:w-5/6 bg-white shadow-heavy-down rounded-md mx-auto -mt-[10rem] px-5 py-10 md:p-10">
      <div class="md:flex gap-10">
         <img src="{{ seller.image.url }}" alt="Seller Profile Image - {{ seller.store_name }}" class="w-44 h-44 lg:w-52 lg:h-52 rounded-full object-cover">
         <div class="md:px-0 pt-5 lg:pt-10">
            <h1 class="text-2xl md:text-3xl lg:text-4xl font-bold mb-4">{{ seller.store_name }}</h1>
            <table class="text-base lg:text-lg">
               <tr>
                  <td>Location</td>
                  <td class="px-5">:</td>
                  <td>{{ seller.location }}</td>
               </tr>
               <tr>
                  <td>Phone Number</td>
                  <td class="px-5">:</td>
                  <td>{{ seller.phone_number }}</td>
               </tr>
            </table>
            <a href="{% url 'Seller:edit_seller_account' seller.user.id %}" class="inline-block border border-neutral-700 mt-5 px-7 py-2 text-sm transition-all hover:bg-neutral-800 hover:text-white">Edit Profile</a>
         </div>
      </div>
      <div class="mt-10 mb-4 px-0 md:px-5">
         <h2 class="font-semibold text-xl mb-2">Description: </h2>
         <p>{{ seller.desc }}</p>
      </div>
   </section>
   <section class="w-5/6 mx-auto mt-20">
      <div class="flex items-center justify-between mb-12">
         <h1 class="text-2xl md:text-3xl lg:text-4xl font-bold">Your Books</h1>
         <a href="{% url 'Seller:add_product' %}" class="border border-green-700 px-4 py-2 text-sm md:text-base transition-all hover:bg-green-600 hover:text-white">Add New Product</a>
      </div>
      {% include 'library/product_div.html' %}
   </section>
</main>
{% endblock %}

templates/seller/add_product.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}Add Your New Product{% endblock %}

{% block content %}
<main class="w-11/12 semi-lg:w-5/6 2xl:w-3/4 mx-auto py-28 md:py-32">
   <h1 class="text-3xl font-bold">Add Your New Product Here</h1>
   <form method="post" class="mt-7">
      {% csrf_token %}
      <input type="hidden" name="seller" value="{{ user.id }}">
      <div class="md:flex gap-[2%] semi-lg:gap-[4%]">
         <div class="max-w-[450px] md:max-w-none md:w-[49%] semi-lg:w-[48%]">
            <div class="mb-4">
               <label for="id_name" class="block font-semibold mb-1">Name:</label>
               {{ form.name }}
               <small class="block mt-1 text-red-600">{{ form.name.errors }}</small>
            </div>
            <div class="mb-4">
               <label for="id_author" class="block font-semibold mb-1">Author:</label>
               {{ form.author }}
               <small class="block mt-1 text-red-600">{{ form.author.errors }}</small>
            </div>
            <div class="mb-4" id="category_input_wrapper">
               <label for="id_category" class="block font-semibold mb-1">Category:</label>
               {{ form.category }}
               <div class="relative">
                  <p class="block w-full border border-slate-500 px-3 py-2 text-sm cursor-pointer">- Click To Select -</p>
                  <div class="hidden absolute top-full -translate-y-4 w-full max-h-[350px] bg-white border border-slate-400 overflow-auto opacity-0 transition-all duration-300" id="category_select">
                     {% for category in fictional_categories %}
                     <option data-category-id="{{ category.id }}" class="block w-full p-3 text-sm cursor-pointer hover:bg-slate-200">{{ category.name }}</option>
                     {% endfor %}
                     {% for category in nonfictional_categories %}
                     <option data-category-id="{{ category.id }}" class="block w-full p-3 text-sm cursor-pointer hover:bg-slate-200">{{ category.name }}</option>
                     {% endfor %}
                  </div>
               </div>
               <small class="block mt-1 text-red-600">{{ form.category.errors }}</small>
            </div>
            <div class="mb-4">
               <label for="id_desc" class="block font-semibold mb-1">Desc:</label>
               {{ form.desc }}
               <small class="block mt-1 text-red-600">{{ form.desc.errors }}</small>
            </div>
            <div class="mb-4">
               <label for="id_publisher" class="block font-semibold mb-1">Publisher:</label>
               {{ form.publisher }}
               <small class="block mt-1 text-red-600">{{ form.publisher.errors }}</small>
            </div>
            <div class="flex gap-[2%] mb-4">
               <div class="w-[49%]">
                  <label for="id_publish_year" class="block font-semibold mb-1">Publish Year:</label>
                  {{ form.publish_year }}
                  <small class="block mt-1 text-red-600">{{ form.publish_year.errors }}</small>
               </div>
               <div class="w-[49%]">
                  <label for="id_stock" class="block font-semibold mb-1">Stock:</label>
                  {{ form.stock }}
                  <small class="block mt-1 text-red-600">{{ form.stock.errors }}</small>
               </div>
            </div>
         </div>
         <div class="max-w-[450px] md:max-w-none md:w-[49%] semi-lg:w-[48%]">
            <div class="mb-4">
               <label for="id_synopsis" class="block font-semibold mb-1">Synopsis:</label>
               {{ form.synopsis }}
               <small class="block mt-1 text-red-600">{{ form.synopsis.errors }}</small>
            </div>
            <div class="flex gap-[2%] mb-4">
               <div class="w-[49%]">
                  <label for="id_total_pages" class="block font-semibold mb-1">Total pages:</label>
                  {{ form.total_pages }}
                  <small class="block mt-1 text-red-600">{{ form.total_pages.errors }}</small>
               </div>
               <div class="w-[49%]">
                  <label for="id_total_chapters" class="block font-semibold mb-1">Total chapters:</label>
                  {{ form.total_chapters }}
                  <small class="block mt-1 text-red-600">{{ form.total_chapters.errors }}</small>
               </div>
            </div>
            <div class="mb-4">
               <label for="id_size" class="block font-semibold mb-1">Size:</label>
               {{ form.size }}
               <div class="flex items-center gap-[2%] w-full">
                  <input type="text" id="height" class="coma-regexed block w-full border border-slate-500 px-3 py-2 text-sm outline-none size-input" placeholder="height" min="0">
                  <span class="font-bold">x</span>
                  <input type="text" id="width" class="coma-regexed block w-full border border-slate-500 px-3 py-2 text-sm outline-none size-input" placeholder="width" min="0">
                  <span class="font-bold">x</span>
                  <input type="text" id="thickness" class="coma-regexed block w-full border border-slate-500 px-3 py-2 text-sm outline-none size-input" placeholder="thickness" min="0">
               </div>
               <small class="block mt-1 text-red-600">{{ form.size.errors }}</small>
            </div>
            <div class="mb-4">
               <label for="id_serial_number" class="block font-semibold mb-1">Serial number:</label>
               {{ form.serial_number }}
               <small class="block mt-1 text-red-600">{{ form.serial_number.errors }}</small>
            </div>
            <div class="flex gap-[2%] mb-4"> 
               <div class="w-[49%]">
                  <label for="id_weight" class="block font-semibold mb-1">Weight:</label>
                  {{ form.weight }}
                  <small class="block mt-1 text-red-600">{{ form.weight.errors }}</small>
               </div>
               <div class="w-[49%]">
                  <label for="id_price" class="block font-semibold mb-1">Price:</label>
                  {{ form.price }}
                  <small class="block mt-1 text-red-600">{{ form.price.errors }}</small>
               </div>
            </div>
         </div>
      </div>
      <div class="flex justify-end gap-3">
         {% if book_id %}
         <a href="{% url 'Seller:upload_image' book_id %}" class="border border-red-500 rounded-sm px-5 py-2 text-sm text-red-500 transition-all hover:text-white hover:bg-red-500">Re-Upload Image</a>
         {% endif %}
         <button class="border border-red-500 rounded-sm px-5 py-2 text-sm text-red-500 transition-all hover:text-white hover:bg-red-500">Add Product</button>
      </div>
   </form>
</main>

<script src="{% static 'js/seller.js' %}"></script>
{% endblock %}

templates/seller/customer_order.html
{% extends 'layout.html' %}
{% load static %}
{% load custom_tags %}

{% block title %}Your Profile Page{% endblock %}

{% block content %}
<main class="w-11/12 md:w-5/6 mx-auto my-28 md:my-32">
   <h1 class="text-2xl sm:text-3xl semi-lg:text-4xl 2xl:text-[40px] font-bold mb-10">On Going Orders</h1>
   {% if orders|length > 0 %}
   {% for order in orders %}
   <div class="w-full semi-lg:w-[90%] shadow-book-div rounded-lg mb-10 overflow-hidden">
      <div class="flex gap-3">
         <div
            class="w-[132px] h-[176px] md:w-[150px] md:h-[200px] xl:w-[174px] xl:h-[232px] 2xl:w-[198px] 2xl:h-[264px] flex-shrink-0">
            {% with order.book|find_main_image as book_main_image %}
            <img src="{{ book_main_image.image.url }}" alt="Image Of '{{ book.name }}' Book"
               class="w-full h-full object-cover rounded-sm">
            {% endwith %}
         </div>
         <div class="p-4 w-full pr-6">
            <h2 class="semi-lg:text-lg font-bold mb-2">{{ order.book.name }}</h2>
            <div class="mb-5 text-[13px] md:text-[15px] italic">
               <p class="my-1"><span class="font-bold">Address</span>: {{ order.address }}</p>
               <p class="my-1"><span class="font-bold">Payment</span>: {{ order.payment_method }}</p>
               <p class="my-1"><span class="font-bold">Shipment</span>: {{ order.shipment_method }}</p>
               <p class="my-1"><span class="font-bold">Status</span>: {{ order.arrival_status }}</p>
            </div>
            <a href="{% url 'Seller:udpate_track' order.id %}" class="border border-red-500 rounded-sm px-5 py-2 text-sm text-red-500 transition-all hover:text-white hover:bg-red-500">Update Tracks</a>
         </div>
      </div>
   </div>
   {% endfor %}
   {% else %}
   <div class="pb-16">
      <p>There is no order on going for now! <a href="{% url 'Library:main' %}" class="text-red-400">Click here</a> to buy new book.</p>
   </div>
   {% endif %}
</main>


{% endblock %}

templates/seller/open_seller_account.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}Open Your New Seller Account. Be a VLibrary Seller Now!{% endblock %}

{% block content %}
<main class="pt-16 md:pt-20 pb-16">
   <div class="w-full h-60 bg-red-200"></div>
   <form class="w-5/6 bg-white shadow-heavy-down rounded-md mx-auto -mt-[10rem] px-5 py-10 md:p-10" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="md:flex gap-10">
         <label class="flex justify-center items-center w-44 h-44 lg:w-52 lg:h-52 border-2 border-neutral-500 rounded-full cursor-pointer overflow-hidden flex-shrink-0" for="id_image">
            <span class="text-xl" id="upload_image_button_h2">Upload image</span>
            <img src="" class="w-full h-full rounded-full object-cover hidden" id="uploaded_image">
         </label>
         {{ form.image }}
         <div class="w-full lg:w-3/5 pt-10">
            <h1 class="text-2xl md:text-3xl lg:text-4xl font-bold mb-4">
               {{ form.store_name }}
            </h1>
            <table class="w-full lg:text-lg">
               <tr>
                  <td class="w-[110px] md:w-[130px]">Location</td>
                  <td class="w-[10px] px-5 py-2">:</td>
                  <td>{{ form.location }}</td>
               </tr>
               <tr>
                  <td class="w-[110px] md:w-[130px]">Phone Number</td>
                  <td class="w-[10px] px-5 py-2">:</td>
                  <td>{{ form.phone_number }}</td>
               </tr>
            </table>
         </div>
      </div>
      <div class="mb-10 mt-4 md:px-5">
         <small class="text-base text-red-600">{{ form.image.errors }}</small>
         <small class="text-base text-red-600">{{ form.location.errors }}</small>
         <small class="text-base text-red-600">{{ form.phone_number.errors }}</small>
      </div>
      <div class="mt-10 mb-4 md:px-5">
         <h2 class="font-semibold text-xl mb-2">Description: </h2>
         {{ form.desc }}
         <small class="text-base text-red-600">{{ form.desc.errors }}</small>
      </div>
      <div class="flex justify-end mb-4 md:px-5">
         <button class="border border-neutral-500 px-7 py-2 text-sm hover:text-white hover:bg-neutral-800">
            Become A Seller
         </button>
      </div>
   </form>
</main>

<script src="{% static 'js/seller.js' %}"></script>
{% endblock %}