Library/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from.views import MainIndex, BookDetailPage, PurchasePage, PaymentProcessPage, FeedbackReportPage, add_to_cart, CategoryBasedPage


app_name = 'Library'
urlpatterns = [
   path('', MainIndex.as_view(), name="main"),
   path('book/<pk>', BookDetailPage.as_view(), name="book_detail"),
   path('purchase_book/<book_id>', login_required(PurchasePage.as_view()), name='purchase'),
   path('purchase_book/payment_process/<address>/<shipment_method>/<payment_method>/<book_id>', login_required(PaymentProcessPage.as_view()), name='payment_process'),
   path('feedback-report/contact-us', FeedbackReportPage.as_view(), name='feedback_report'),
   path('book/add-to-cart/<book_id>', add_to_cart, name="add_to_cart"),
   path('category/<category_id>', CategoryBasedPage.as_view(), name="category_based")
]

User/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import WelcomePage, SignUpPage, SignInPage, LogoutPage, ProfilePage, AboutAccountPage, PrivacySecurityPage, SetAddressPage, TransactionHistory, UserCartList

app_name = "User"
urlpatterns = [
   path('', WelcomePage.as_view(), name='welcome'),
   path('sign-up', SignUpPage.as_view(), name='sign_up'),
   path('sign-in', SignInPage.as_view(), name='sign_in'),
   path('user/logout', login_required(LogoutPage.as_view()), name='logout'),
   path('user/profile', login_required(ProfilePage.as_view()), name='profile'),
   path('user/profile/about-account', login_required(AboutAccountPage.as_view()), name='about_account'),
   path('user/profile/privacy-security', login_required(PrivacySecurityPage.as_view()), name='privacy_security'),
   path('user/profile/set-address', login_required(SetAddressPage.as_view()), name='set_address'),
   path('user/history/transaction', login_required(TransactionHistory.as_view()), name='transaction_history'),
   path('user/cart/list', login_required(UserCartList.as_view()), name='cart_list'),
]

templates/index.html
{% extends 'layout.html' %}
{% load static %}
{% load custom_tags %}

{% block title %}Welcome To VLibrary{% endblock %}

{% block content %}

<main class="relative w-full min-h-screen flex md:items-center pt-32 md:pt-5">
   <section class="w-5/6 2xl:w-3/4 mx-auto">
      <div class="flex flex-shrink-0 gap-10 lg:gap-20 justify-evenly md:items-center w-full sm:w-5/6 md:w-full mx-auto z-10">
         <img src="{% static 'image/jumbotron_img1.png' %}" alt="Books Image" class="hidden md:block transition-all duration-300 h-[300px] lg:h-[400px]" id="jumbotron_img1">
         <div class="h-[275px] md:h-[320px] lg:h-[400px] w-2 bg-red-700 rounded-full shadow-shining-red flex-shrink-0"></div>
         <div class="py-5">
            <h1 class="w-full capitalize font-bold text-4xl md:text-5xl lg:text-[52px] xl:text-6xl text-balance transition-all duration-300">What book are you searching for?</h1>
            <form action="" class="mt-5">
               <input type="text" class="w-full bg-transparent border-2 border-slate-800 py-[6px] md:py-2 px-3 rounded-md outline-none shadow-md placeholder:text-slate-500" placeholder="Click here to search a book" id="search_book_input">
               <button class="bg-red-600 shadow-sm shadow-red-700 rounded-md mt-2 px-10 py-2 text-white text-sm transition-all hover:scale-105 hover:shadow-md hover:shadow-red-600">Search</button>
            </form>
         </div>
      </div>
      <img src="{% static 'image/jumbotron_img2.png' %}" alt="Books Image" class="absolute bottom-0 left-1/2 -translate-x-1/2 md:hidden h-[300px]" id="jumbotron_img2">
      <div class="absolute left-0 bottom-0 w-full h-32 translate-y-12 bg-gradient-to-t from-white to-transparent"></div>
   </section>
</main>

<section class="flex flex-shrink-0 flex-wrap justify-evenly pt-16 pb-[170px] semi-lg:pb-[220px] lg:pb-[300px]" id="introduction">
   <div class="w-4/5 sm:w-[45%] semi-lg:w-[31%] lg:w-[28%] bg-red-500 rounded-md shadow-down-red p-10 text-white self-start translate-y-[100px] opacity-0 transition-all duration-500">
      <h1 class="font-bold text-xl lg:text-2xl mb-3">Why is it important to read book?</h1>
      <p class="text-sm xl:text-base">Reading book gives you bunch of benefit. It is not only for entertainment purposes, but it is also for getting more important knowledge that you can learn without experiencing it directly</p> </div>
   <div class="w-4/5 sm:w-[45%] semi-lg:w-[31%] lg:w-[28%] bg-red-500 rounded-md shadow-down-red p-10 text-white translate-y-[135px] semi-lg:translate-y-[170px] lg:translate-y-[200px] self-start opacity-0 transition-all duration-500">
      <h1 class="font-bold text-xl lg:text-2xl mb-3">Want to find information?</h1>
      <p class="text-sm xl:text-base">There are lots of things that you never knew before, and now you know from reading a specific information. One of the biggest way to get important information is through reading book. As the saying goes, the more you know, the more you don't know anything. Read more, and you will learn more.</p> </div>
   <div class="w-4/5 semi-lg:w-[31%] lg:w-[28%] bg-red-500 rounded-md shadow-down-red p-10 text-white translate-y-[169px] semi-lg:translate-y-[240px] lg:translate-y-[300px] self-start opacity-0 transition-all duration-500">
      <h1 class="font-bold text-xl lg:text-2xl mb-3">Experience from others?</h1>
      <p class="text-sm xl:text-base">Everything you put in your mind will always effect the way you face life events. The more you learn from other people's experience, the more knowledge you can gain from them. There are lots of tips and trick that is given by the author. There is also bunch of strategy to gain experience.</p>
   </div>
</section>

<section class="w-5/6 mx-auto mb-32" id="motivational_quote">
   <h1 class="font-bold text-red-900 text-2xl md:text-3xl lg:text-4xl mb-6 opacity-0 transition-all duration-500">Quotes To Help You Grow !!!</h1>
   <div class="overflow-hidden opacity-0 translate-y-[100px] transition-all duration-500 my-3" id="quotes_wrapper">
      <div class="flex transition-all duration-500">
         {% for quote in quotes %}
         <blockquote class="w-full semi-lg:w-1/2 p-5 flex-shrink-0">
            <div class="w-full h-full bg-slate-200 rounded-md p-7">
               <q class="text-xl lg:text-[23px] font-semibold">{{ quote.message }}</q>
               <h2 class="text-lg font-semibold text-slate-700 mt-2">- {{ quote.author }} -</h2>
            </div>
         </blockquote>
         {% endfor %}
      </div>
   </div>
   </div>
   <nav class="flex justify-center gap-2 mt-7 opacity-0 transition-all duration-500" id="quotes_nav">
      {% with quotes|length as num_of_quotes %}
      {% with ''|center:num_of_quotes as range %}
      {% for _ in range %}
         {% if forloop.counter0 == 0 %}
         <button class="w-3 h-3 border-2 border-slate-400 rounded-full quote_link bg-slate-600 outline-none"></button>
         {% else %}
         <button class="w-3 h-3 border-2 border-slate-400 rounded-full quote_link hover:bg-slate-300  outline-none
         {% if forloop.counter > quotes|length|divide %} inline-block semi-lg:hidden {% endif %}"></button>
         {% endif %}
      {% endfor %}
      {% endwith %}
      {% endwith %}
   </nav>
</section>

<footer class="w-full bg-red-500">
   <div class="w-5/6 flex justify-between flex-wrap gap-[10%] mx-auto pt-14 pb-4 md:pb-14 px-5 text-white">
      <div class="w-full sm:w-[45%] md:w-auto">
         <h1 class="text-xl md:text-[22px] lg:text-2xl font-bold">CAPRIGO CORPORATION</h1>
         <h3 class="text-slate-300 text-lg">Developer: Andy yang</h3>
         <div class="flex flex-col gap-3 mt-5 text-sm md:text-base">
            <a href="" class="hover:underline">Help</a>
            <a href="" class="hover:underline">Contact Us</a>
         </div>
      </div>
      <div class="w-full sm:w-[45%] md:w-auto lg:w-1/4 mt-10 sm:mt-0">
         <h2 class="text-xl md:text-[22px] lg:text-2xl font-bold">Service Used</h2>
         <div class="flex flex-col gap-4 mt-5 text-sm md:text-base">
            <a href="https://www.googleadservices.com/pagead/aclk?sa=L&ai=DChcSEwiGzrC5076BAxUBaH0KHc-tC9EYABAAGgJzZg&gclid=Cj0KCQjw9rSoBhCiARIsAFOipln2pgBFe2FUX2l7G8IaMPWQOgNiXvFr9e2g85YT0HIk8aqYTtXEBsQaAgq3EALw_wcB&ohost=www.google.com&cid=CAESa-D2X8X4agGMy37s0xjr9A8oIZr1C1vsSQY3GeXaZHq6SUnon2RaFjMJXBasRzDxQKadldZ-t1vmL0RdsbTmnY8hDJqZtdHPGIeVlAuF9rpCn83a3ynWH8yXbgVa0zZHjaGfzApdQEss-3WM&sig=AOD64_2sB1EkvikZSyzjZvVIqIQoQNH33Q&q&adurl&ved=2ahUKEwjP9Kq5076BAxUCSmwGHRfKDMcQ0Qx6BAgNEAE" class="hover:underline">Gencraft</a>
            <a href="https://freeicons.io/" class="hover:underline">Freeicons</a>
            <a href="https://onlinepngtools.com/create-transparent-png" class="hover:underline">OnlinePNGTools</a>
            <a href="https://www.canva.com/colors/color-wheel/" class="hover:underline">Canva's Color Wheel</a>
         </div>
      </div>
      <div class="w-full md:w-auto flex justify-center gap-10 sm:gap-20 md:gap-5 md:block mt-10 md:mt-0">
         <div class="w-10 h-10 bg-white border-2 border-white rounded-full my-3">
            <img src="{% static 'image/icons/youtube.png' %}" alt="Youtube Account" class="w-full h-full">
         </div>
         <div class="w-10 h-10 bg-white border-2 border-white rounded-full my-3">
            <img src="{% static 'image/icons/github.png' %}" alt="Github Account" class="w-full h-full">
         </div>
         <div class="w-10 h-10 bg-white border-2 border-white rounded-full my-3">
            <img src="{% static 'image/icons/instagram.png' %}" alt="Instagram Account" class="w-full h-full">
         </div>
      </div>
   </div>
</footer>

<script src="{% static 'js/user.js' %}"></script>

{% endblock %}

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>{% block title %}{% endblock %}</title>

   <!-- main css -->
   <link rel="stylesheet" href="{% static '/css/style.css' %}">
   <link rel="stylesheet" href="{% static '/css/pure_css.css' %}">

   <!-- fonts -->
   <link rel="preconnect" href="https://fonts.googleapis.com">
   <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
   <link href="https://fonts.googleapis.com/css2?family=Courgette&family=Nunito+Sans:opsz,wght@6..12,300;6..12,400;6..12,600;6..12,700&family=Pacifico&display=swap" rel="stylesheet">

   <!-- jquery -->
   <script src="{% static 'js/jquery.js' %}"></script>
   <script src="{% static 'js/navbar.js' %}"></script>
   <script src="{% static 'js/layout.js' %}"></script>
</head>

<body class="font-main">
   
   {% if not auth_page %}
   {% include 'navbar.html' %}
   {% endif %}
   
   {% block content %}{% endblock %}

   <div id="dark_bg" class="hidden fixed top-0 left-0 w-full min-h-screen bg-slate-900 opacity-0 z-[50] transition-all duration-500"></div>

   {% if messages %}
   {% for message in messages %}
   <div class="fixed bottom-10 left-10 max-w-[400px] semi-lg:max-w-[550px] bg-white shadow-around rounded-md p-5 text-sm sm:text-[15px] semi-lg:text-base translate-y-[200%] animate-flash-pop-up">
      <p>{{ message }}</p>
   </div>
   {% endfor %}
   {% endif %}
   
</body>

</html>

templates/navbar.html
{% load static %}
{% load custom_tags %}
<nav class="fixed flex items-center w-full top-0 bg-white border-b border-slate-400 z-[90]">
   <div class="flex gap-12 semi-lg:gap-28 xl:gap-40 justify-between w-[94%] sm:w-[87%] lg:w-5/6 h-16 md:h-20 mx-auto">
      <header class="flex gap-1 items-center">
         <img src="{% static 'image/logo.png' %}" class="w-10 md:w-12" alt="website logo - VLibrary logo">
         <h1 class="font-bold text-xl md:text-2xl font-logo2 text-red-800">
            <a href="{% url 'Library:main' %}">
               <span class="mr-1 font-logo1 text-orange-700">V</span>Library
            </a>
         </h1>
      </header>
      <menu class="flex md:min-w-[550px] md:w-full justify-between relative">
         <section class="hidden h-full md:flex">
            <button class="font-semibold w-28 lg:w-36 h-full relative after:top-0 after:left-1/2 after:absolute after:h-[5px] after:w-0 after:bg-red-400 after:rounded-full after:transition-all after:duration-300 hover:after:w-full hover:after:left-0" id="category_menu_btn">Category</button>
            <button class="font-semibold w-28 lg:w-36 h-full relative after:top-0 after:left-1/2 after:absolute after:h-[5px] after:w-0 after:bg-red-400 after:rounded-full after:transition-all after:duration-300 hover:after:w-full hover:after:left-0" id="history_menu_btn">History</button>
            <button class="font-semibold w-28 lg:w-36 h-full relative after:top-0 after:left-1/2 after:absolute after:h-[5px] after:w-0 after:bg-red-400 after:rounded-full after:transition-all after:duration-300 hover:after:w-full hover:after:left-0" id="cart_menu_btn">Cart</button>
         </section>

         <section class="flex gap-6 xl:gap-10 items-center pr-2 text-sm">
            {% if user.is_authenticated %}
            <a href="{% url 'User:logout' %}" class="text-slate-800 font-semibold transition-all hover:text-red-800">Logout</a>
            <a href="{% url 'User:profile' %}" class="border border-red-900 rounded-md px-5 md:px-7 py-[6px] md:py-2 text-slate-900 font-semibold transition-all hover:bg-red-200">Profile</a>
            {% else %}
            <a href="{% url 'User:sign_in' %}" class="text-slate-800 font-semibold transition-all hover:text-red-800">Sign In</a>
            <a href="{% url 'User:sign_up' %}" class="border border-red-900 rounded-md px-5 md:px-7 py-[6px] md:py-2 text-slate-900 font-semibold transition-all hover:bg-red-200">Sign Up</a>
            {% endif %}
            <button class="md:hidden z-10" id="hamburger_button">
               <span class="block w-8 h-1 bg-red-400 rounded-full my-1 transition-all duration-300 origin-left"></span>
               <span class="block w-8 h-1 bg-red-400 rounded-full my-1 transition-all duration-300"></span>
               <span class="block w-8 h-1 bg-red-400 rounded-full my-1 transition-all duration-300 origin-left"></span>
            </button>

            <nav class="md:hidden hidden fixed top-0 -right-5 w-[400px] h-full bg-white transition-all duration-700 shadow-around translate-x-full" id="small_nav">
               <h1 class="text-2xl font-bold px-10 h-16 leading-[64px] border-b border-red-300">Menu</h1>
               <div class="overflow-auto small-scrollbar" id="small_nav_wrapper">
                  <a href="{% url 'User:transaction_history' %}" class="block px-10 py-4 text-lg hover:bg-red-50 hover:font-bold hover:text-red-800">History</a>
                  <a href="{% url 'User:cart_list' %}" class="block px-10 py-4 text-lg hover:bg-red-50 hover:font-bold hover:text-red-800">Cart</a>
                  <div class="px-10 pt-5 pb-10">
                     <h2 class="font-bold text-lg text-red-800 mb-8">Category</h2>
                     <div class="pl-7">
                        <section>
                           <h1 class="font-semibold text-[17px] mt-3 mb-1">Fictional Book</h1>
                           <div>
                              {% for category in fictional_categories %}
                              <a href="{% url 'Library:category_based' category.id %}" class="inline-block w-[49%] my-3">{{ category.name }}</a>
                              {% endfor %}
                           </div>
                        </section>
                        <section>
                           <h1 class="font-semibold text-[17px] mt-3 mb-1">Non-fictional Book</h1>
                           <div>
                              {% for category in nonfictional_categories %}
                              <a href="{% url 'Library:category_based' category.id %}" class="inline-block w-[49%] my-3">{{ category.name }}</a>
                              {% endfor %}
                           </div>
                        </section>
                     </div>
                  </div>
               </div>
            </nav>
         </section>

         {% include 'navbar_menu_hover.html' %}
      </menu>
   </div>
</nav>

templates/navbar_menu_hover.html
{% load static %}
{% load custom_tags %}
<div class="hidden md:hidden absolute top-full left-0 w-full bg-white shadow-around rounded-md px-10 py-6 opacity-0 scale-[0.98] translate-y-1 transition-all duration-300 
         after:absolute after:top-0 after:left-[45px] lg:after:left-[60px] after:-translate-y-3 after:border-x-[12px] after:border-x-transparent after:border-b-[12px] after:border-b-white nav_menu_wrapper"
   id="category_menu_wrapper">
   <section>
      <h1 class="font-bold text-lg mt-3 mb-1 text-red-800">Fictional Book</h1>
      <div>
         {% for category in fictional_categories %}
         <a href="{% url 'Library:category_based' category.id %}" class="inline-block w-[110px] lg:w-[125px] text-center text-[15px] lg:text-base py-5 transition-all hover:text-red-700 hover:scale-110 hover:font-bold">{{ category.name }}</a>
         {% endfor %}
      </div>
   </section>
   <section>
      <h1 class="font-bold text-lg mt-3 mb-1 text-red-800">Non-fictional Book</h1>
      <div>
         {% for category in nonfictional_categories %}
         <a href="{% url 'Library:category_based' category.id %}" class="inline-block w-[110px] lg:w-[125px] text-center text-[15px] lg:text-base py-5 transition-all hover:text-red-700 hover:scale-110 hover:font-bold">{{ category.name }}</a>
         {% endfor %}
      </div>
   </section>
</div>

<div
   class="hidden md:hidden absolute top-full left-0 w-full bg-white shadow-around rounded-md px-10 py-6 opacity-0 scale-[0.98] translate-y-1 transition-all duration-300 
         after:absolute after:top-0 after:left-[160px] lg:after:left-[205px] after:-translate-y-3 after:border-x-[12px] after:border-x-transparent after:border-b-[12px] after:border-b-white nav_menu_wrapper"
   id="history_menu_wrapper">
   <section class="mb-5">
      <h2 class="flex items-center gap-2 mt-3 mb-5 text-red-800">
         <img src="{% static 'image/icons/history.png' %}" class="w-5 h-5 filter-to-red transition-all duration-300">
         <span class="font-bold text-xl">Your History</span>
      </h2>
      <div class="max-h-[420px] overflow-auto gray-scrollbar px-3">
         {% if transaction_history|length > 0 %}
         {% for transaction in transaction_history %}
         <div class="shadow-book-div rounded-md overflow-hidden mb-4">
            <div class="flex gap-2">
               <div class="flex-shrink-0 w-[90px] h-[120px]">
                  {% with transaction.book|find_main_image as book_main_image %}
                  <img src="{{ book_main_image.image.url }}" alt="Image Of '{{ transaction.book.name }}' Book"
                     class="w-full h-full object-cover rounded-sm">
                  {% endwith %}
               </div>
               <div class="p-2">
                  <h2 class="transition-all hover:text-red-700">
                     <a href="{% url 'Library:book_detail' transaction.book.id %}">{{ transaction.book.name }}</a>
                  </h2>
                  <div class="flex gap-8 text-sm italic">
                     <div>
                        <p class="my-[2px]">
                           <span class="font-bold">Address</span>: {{ transaction.address }}</p>
                        <p class="my-[2px]">
                           <span class="font-bold">Arrival Date</span>: {{ transaction.arrive_date|date:'j F Y' }}
                        </p>
                     </div>
                     <div>
                        <p class="my-[2px]">
                           <span class="font-bold">Shipment</span>: {{ transaction.shipment_method }}
                        </p>
                        <p class="my-[2px]">
                           <span class="font-bold">Payment</span>: {{ transaction.payment_method }}
                        </p>
                     </div>
                  </div>
                  <p class="my-[2px] text-sm italic text-green-600">
                     <span class="text-xs">$</span><span class="pl-1 font-bold">{{ transaction.book.price }}</span>
                  </p>
               </div>
            </div>
         </div>
         {% endfor %}
         {% else %}
         <div class="mt-2">No transactions yet in your account. Purchase something until it has arrived and the
            transaction will be recorded here.</div>
         {% endif %}
      </div>
   </section>
</div>

<div class="hidden md:hidden absolute top-full left-0 w-full bg-white shadow-around rounded-md px-10 py-6 opacity-0 scale-[0.98] translate-y-1 transition-all duration-300 
         after:absolute after:top-0 after:left-[270px] lg:after:left-[350px] after:-translate-y-3 after:border-x-[12px] after:border-x-transparent after:border-b-[12px] after:border-b-white nav_menu_wrapper"
   id="cart_menu_wrapper">
   <section class="mb-5">
      <h2 class="flex items-center gap-2 mt-3 mb-5 text-red-800">
         <img src="{% static 'image/icons/cart.png' %}" class="w-5 h-5 filter-to-red transition-all duration-300">
         <span class="font-bold text-xl">Your Cart</span>
      </h2>
      <div class="max-h-[420px] overflow-auto gray-scrollbar px-3" id="cart_list_wrapper">
         {% include 'library/cart_list_hover.html' %}
      </div>
   </section>
</div>