Library/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from.views import MainIndex, BookDetailPage, PurchasePage, PaymentProcessPage, FeedbackReportPage, add_to_cart, CategoryBasedPage


app_name = 'Library'
urlpatterns = [
   path('', MainIndex.as_view(), name="main"),
   path('book/<pk>', BookDetailPage.as_view(), name="book_detail"),
   path('purchase_book/<book_id>', login_required(PurchasePage.as_view()), name='purchase'),
   path('purchase_book/payment_process/<address>/<shipment_method>/<payment_method>/<book_id>', login_required(PaymentProcessPage.as_view()), name='payment_process'),
   path('feedback-report/contact-us', FeedbackReportPage.as_view(), name='feedback_report'),
   path('book/add-to-cart/<book_id>', add_to_cart, name="add_to_cart"),
   path('category/<category_id>', CategoryBasedPage.as_view(), name="category_based")
]

Seller/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import AddProductPage, OpenSellerAccount, ProductImageUpload, SellerAccountPage, EditSellerAccountPage, EditProductPage, CustomerOrderPage, update_track

app_name = "Seller"
urlpatterns = [
   path('add-product/', login_required(AddProductPage.as_view()), name='add_product'),
   path('edit-product/<pk>', login_required(EditProductPage.as_view()), name='edit_product'),
   path('profile/open-seller-account', login_required(OpenSellerAccount.as_view()), name='open_seller_account'),
   path('product-image-upload/<book_id>', login_required(ProductImageUpload.as_view()), name='upload_image'),
   path('account/<seller_id>', login_required(SellerAccountPage.as_view()), name='account'),
   path('account/edit/<pk>', login_required(EditSellerAccountPage.as_view()), name='edit_seller_account'),
   path('customer_orders/', login_required(CustomerOrderPage.as_view()), name="customer_orders"),
   path('order/udpate_track/<order_id>', login_required(update_track), name="udpate_track"),
]

User/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import WelcomePage, SignUpPage, SignInPage, LogoutPage, ProfilePage, AboutAccountPage, PrivacySecurityPage, SetAddressPage, TransactionHistory, UserCartList

app_name = "User"
urlpatterns = [
   path('', WelcomePage.as_view(), name='welcome'),
   path('sign-up', SignUpPage.as_view(), name='sign_up'),
   path('sign-in', SignInPage.as_view(), name='sign_in'),
   path('user/logout', login_required(LogoutPage.as_view()), name='logout'),
   path('user/profile', login_required(ProfilePage.as_view()), name='profile'),
   path('user/profile/about-account', login_required(AboutAccountPage.as_view()), name='about_account'),
   path('user/profile/privacy-security', login_required(PrivacySecurityPage.as_view()), name='privacy_security'),
   path('user/profile/set-address', login_required(SetAddressPage.as_view()), name='set_address'),
   path('user/history/transaction', login_required(TransactionHistory.as_view()), name='transaction_history'),
   path('user/cart/list', login_required(UserCartList.as_view()), name='cart_list'),
]

Library/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.utils import timezone
from navigation.models import Category
from Seller.models import Seller

# Create your models here.
def minimum_price(value):
   if value > 0:
      return value
   else:
      return ValidationError('Please input price of more than $0')


class Book(models.Model):
   name           = models.CharField(max_length=255, unique=True)
   author         = models.CharField(max_length=150)
   category       = models.ForeignKey(Category, on_delete=models.CASCADE)
   desc           = models.TextField(blank=True)
   synopsis       = models.TextField(blank=True)
   publisher      = models.CharField(max_length=150)
   total_pages    = models.PositiveIntegerField()
   total_chapters = models.PositiveIntegerField()
   publish_year   = models.PositiveIntegerField()
   stock          = models.PositiveIntegerField()
   weight         = models.PositiveIntegerField()
   size           = models.CharField(max_length=100)
   serial_number  = models.CharField(max_length=13)
   price          = models.DecimalField(decimal_places=2, max_digits=10,validators=[minimum_price])
   created_at     = models.DateTimeField(auto_now_add=True)
   seller         = models.ForeignKey(Seller, on_delete=models.CASCADE, blank=True)
   book_activated = models.BooleanField(default=0)

   def __str__(self):
      return f"{self.name} | ${self.price}"


class BookPicture(models.Model):
   image         = models.ImageField(upload_to='book_picture/')
   book          = models.ForeignKey(Book, on_delete=models.CASCADE)
   is_main_image = models.BooleanField(default=False)

   def __str__(self):
      return f"Image for {self.book.name}"


class Transaction(models.Model):
   address         = models.CharField(max_length=150)
   payment_method  = models.CharField(max_length=100)
   shipment_method = models.CharField(max_length=100)
   book            = models.ForeignKey(Book, on_delete=models.CASCADE)
   user            = models.ForeignKey(User, on_delete=models.CASCADE)
   seller          = models.ForeignKey(Seller, on_delete=models.CASCADE)
   created_at      = models.DateTimeField(auto_now_add=True)
   arrival_status  = models.CharField(max_length=50, default="Waiting For Confirmations")
   arrive_date     = models.DateField(blank=True, null=True)
   # Waiting For Confirmations
   # Currently On Shipping
   # Book Arrived!

   
   def __str__(self):
      return f"{self.book.name} | {self.user.username} - {self.address}"

   def save(self, *args, **kwargs):
      if self.arrival_status == 'Book Arrived!':
         self.arrive_date = timezone.now()
      super(Transaction, self).save(*args, **kwargs)


class FeedbackReport(models.Model):
   name    = models.CharField(max_length=150)
   email   = models.EmailField()
   message = models.TextField()

   def __str__(self):
      return "Message from " + self.name


class BookRating(models.Model):
   user   = models.ForeignKey(User, on_delete=models.CASCADE)
   book   = models.ForeignKey(Book, on_delete=models.CASCADE)
   rating = models.FloatField()

   def __str__(self):
      return f"{self.rating} for {self.book.name} | by {self.user.username}"

Seller/models.py
from django.db import models
from PIL import Image
from User.models import User

# Create your models here.
class Seller(models.Model):
   user           = models.OneToOneField(User, primary_key=True, on_delete=models.CASCADE, related_name='seller_account')
   store_name     = models.CharField(max_length=100)
   phone_number   = models.CharField(max_length=12)
   desc           = models.TextField()
   image          = models.ImageField(upload_to='store_picture/', null=False)
   location       = models.CharField(max_length=150)
   created_at     = models.DateTimeField(auto_now_add=True)
   account_active = models.BooleanField(default=False)

   def __str__(self):
      return f"{self.store_name} From Account - {self.user.username}"
   
   def save(self, *args, **kwargs):
      super(Seller, self).save(*args, **kwargs)
      if self.image:
         image = Image.open(self.image.path)
         image.thumbnail((230, 230))
         image.save(self.image.path)

Library/forms.py
from django import forms
from .models import Transaction, FeedbackReport

class TransactionForm(forms.ModelForm):
   class Meta:
      model = Transaction
      fields = ['address', 'shipment_method', 'payment_method']
      widgets = {
         'address': forms.TextInput(attrs={
            'class': 'w-full border border-neutral-600 p-2 mt-2 outline-none text-sm md:text-base',
            'placeholder': 'insert your address'
         }),
         'shipment_method': forms.HiddenInput(),
         'payment_method': forms.HiddenInput()
      }
      error_messages = {
         'address': { 'required': ['Please input your address'] },
         'payment_method': { 'required': ['Please input your payment method'] },
         'shipment_method': { 'required': ['Please input your shipping method'] }
      }

class FeedbackReportForm(forms.ModelForm):
   class Meta:
      model = FeedbackReport
      fields = "__all__"
      widgets = {
         'name': forms.TextInput(attrs={'class': 'w-full border border-neutral-500 rounded-sm my-1 p-2 text-sm outline-none'}),
         'email': forms.EmailInput(attrs={'class': 'w-full border border-neutral-500 rounded-sm my-1 p-2 text-sm outline-none'}),
         'message': forms.Textarea(attrs={'class': 'w-full border border-neutral-500 rounded-sm my-1 p-2 text-sm outline-none resize-none'})
      }

Library/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, DetailView, CreateView, FormView, View
from django.contrib import messages
from django.http import HttpResponse
from navigation.models import Category
from .models import Book, BookPicture, Transaction
from .forms import TransactionForm, FeedbackReportForm
from datetime import datetime, timedelta
import json


# Create your views here.
class MainIndex(TemplateView):
   template_name = 'library/index.html'

   def get(self, request, *args, **kwargs):
      books = Book.objects.filter(book_activated=1).order_by('-id')

      if 'search' in request.GET:
         books = Book.objects.filter(book_activated=1, name__contains=request.GET['search']).order_by('-id')
      
      return render(request, self.template_name, {
         'books': books
      })

class BookDetailPage(DetailView):
   template_name = 'library/book_detail.html'
   model = Book

   def get_recommended_book(self, book):
      query_1 = Book.objects.\
               filter(category=book.category, book_activated=1).\
               order_by('-id').\
               exclude(id=book.id)[:10]

      additional_book = 10 - len(query_1)
      
      query_2 = Book.objects.\
               exclude(category=book.category, book_activated=1).\
               order_by('-id')[:additional_book]

      return query_1.union(query_2)

   def get(self, request, *args, **kwargs):
      try: 
         book = Book.objects.filter(book_activated=1).get(pk=kwargs['pk'])
      except:
         messages.error(request, "The book you are searching is not found!")
         return redirect("Library:main")

      details = [
         {'title': 'Author'        , 'value': book.author},
         {'title': 'Category'      , 'value': book.category.name},
         {'title': 'Publisher'     , 'value': book.publisher},
         {'title': 'Total Page'    , 'value': book.total_pages},
         {'title': 'Total Chapters', 'value': book.total_chapters},
         {'title': 'Publish Year'  , 'value': book.publish_year},
         {'title': 'Weight'        , 'value': str(book.weight) + ' gram'},
         {'title': 'Size'          , 'value': book.size + ' cm'},
         {'title': 'Serial Number' , 'value': book.serial_number}
      ]

      return render(request, self.template_name, {
         'book': book,
         'books': self.get_recommended_book(book),
         'book_pictures': BookPicture.objects.filter(book=book).order_by('-is_main_image'),
         'details': details
      })




class PurchasePage(FormView):
   template_name = 'library/purchase.html'
   form = TransactionForm

   def get_estimation_arrival(self):
      tday = datetime.today()

      def to_date(value):
         return (tday + timedelta(days=value)).strftime('%#d %B %Y')

      return {
         'fast': to_date(3) + ' - ' + to_date(5),
         'normal': to_date(5) + ' - ' + to_date(7),
         'slow': to_date(8) + ' - ' + to_date(11)
      }


   def get(self, request, *args, **kwargs):
      book = Book.objects.get(id=kwargs['book_id'])

      if book.seller.user != request.user:
         form_initial = {'shipment_method': 'Normal Shipment'}
         if 'saved_address' in request.COOKIES:
            form_initial['address'] = request.COOKIES['saved_address']
         return render(request, self.template_name, {
            'form': TransactionForm(initial=form_initial),
            'book': book,
            'estimation': self.get_estimation_arrival()
         })

      messages.warning(request, "WARNING: You cannot purchase your own product!")
      
      return redirect('Library:main')
   
   def post(self, request, *args, **kwargs):
      validated_data = {
         'address'        : request.POST['address'],
         'shipment_method': request.POST['shipment_method'],
         'payment_method' : request.POST['payment_method']
      }
      form = TransactionForm(validated_data)
      if form.is_valid():
         messages.success(request, 'Order Fulfilled, please enter your payment code.')
         return redirect(
            'Library:payment_process',
            address         = form.cleaned_data['address'],
            shipment_method = form.cleaned_data['shipment_method'],
            payment_method  = form.cleaned_data['payment_method'],
            book_id         = request.POST['book_id']
         )
      
      return render(request, self.template_name, {
         'form': form,
         'book': Book.objects.get(id=kwargs['book_id'])
      })



class PaymentProcessPage(FormView):
   template_name = 'library/payment.html'

   def get(self, request, *args, **kwargs):
      page_context = kwargs
      page_context['payment_logo_img'] = kwargs['payment_method'].lower() + '.png'
      
      return render(request, self.template_name, page_context)

   def post(self, request, *args, **kwargs):
      available_payment_method = ['BCA', 'Paypal', 'Ovo']
      avaialbel_shipment_method = ['Normal Shipment', 'Fast Shipment', 'Slow Shipment']
      if kwargs['payment_method'] in available_payment_method and kwargs['shipment_method'] in avaialbel_shipment_method:
         book = Book.objects.get(pk=kwargs['book_id'])

         new_transaction = Transaction(
            address         = kwargs['address'],
            shipment_method = kwargs['shipment_method'],
            payment_method  = kwargs['payment_method'],
            user            = request.user,
            seller          = book.seller,
            book            = book,
         )
         new_transaction.save()
         
         messages.success(request, 'The book has been purchased. Your book will arive soon!!!')
         return redirect('Library:main')
      
      messages.error(request, 'Something went wrong! Please try again..')
      return self.get(request, *args, **kwargs)


class FeedbackReportPage(CreateView):
   template_name = 'library/contact.html'
   form_class = FeedbackReportForm

   def post(self, request, *args, **kwargs):
      form = FeedbackReportForm(request.POST)
      if form.is_valid():
         form.save()
         messages.success(request, "Thanks for your feedback/report. Thanks for supporting us!!!")
         return redirect("Library:feedback_report")
         
      return render(request, self.template_name, {
         'form': form
      })


def add_to_cart(request, book_id):
   book = Book.objects.filter(book_activated=1, id=book_id)

   if book.seller.user != request.user:
      cart_arr = [int(book_id)]

      if 'cart' in request.COOKIES:
         print(request.COOKIES)
         if request.COOKIES['cart'] == '':
            cart_arr = []
         else:
            cart_arr = json.loads(request.COOKIES['cart'])

         if book_id not in request.COOKIES['cart']:         
            cart_arr.append(int(book_id))
         else:
            cart_arr.remove(int(book_id))

      cart_json = json.dumps(cart_arr)

      cart = []
      for x in cart_arr:
         cart.append(Book.objects.get(pk=x))

      response = render(request, 'library/cart_list_hover.html', {
         'cart': cart
      })
      response.set_cookie(key='cart', value=cart_json, expires=60*60*24*365)
      return response
      
   return False



class CategoryBasedPage(TemplateView):
   template_name = 'library/category_based.html'

   def get_context_data(self, **kwargs):
      page_context = super().get_context_data()
      category = Category.objects.get(pk=kwargs['category_id'])
      page_context['books'] = Book.objects.filter(category=category, book_activated=1).order_by('-id')
      page_context['category_name'] = category.name
      return page_context

   

templates/library/book_detail.html
{% extends 'layout.html' %}
{% load static %}
{% load custom_tags %}

{% block title %}Detail: {{ book.name }}{% endblock %}

{% block content %}
<main>
   <div class="relative md:flex gap-6 semi-lg:gap-8 w-11/12 semi-lg:w-5/6 mx-auto py-32">
      <div class="md:sticky top-[85px] w-3/4 max-w-[410px] md:max-w-none md:w-1/2 aspect-[3_/_4] lg:w-[450px] 2xl:w-[550px] self-start shadow-around rounded-md overflow-hidden flex-shrink-0">
         {% for book_image in book_pictures %}
         <img src="{{ book_image.image.url }}" alt="Image Of {{ book.name }}" class="{% if forloop.counter > 1 %} hidden {% endif %} w-full h-full object-cover book_picture" data-image-counter="{{ forloop.counter }}">
         {% endfor %}
         {% if book_pictures|length > 1 %}
         <button class="absolute top-5 right-5 border border-neutral-800 rounded-sm bg-white px-5 py-2 text-sm transition-all hover:bg-neutral-800 hover:text-white" id="toggle_other_image">Other Image</button>
         {% endif %}
      </div>
      <div class="w-full mt-10 md:mt-0">
         <div class="border-b border-neutral-700 pb-5">
            <h1 class="text-[27px] md:text-[32px] semi-lg:text-4xl 2xl:text-[42px] font-bold">{{ book.name }}</h1>
            <div class="flex items-center gap-4 mt-5">
               <img src="{{ book.seller.image.url }}" alt="Seller Profile - {{ book.seller.store_name }}"
                  class="w-10 h-10 2xl:w-11 2xl:h-11 rounded-full object-cover">
               <h2 class="font-semibold text-base 2xl:text-lg">{{ book.seller.store_name }}</h2>
            </div>
         </div>
         <div class="mt-2">
            <div class="py-6">
               <div>
                  <h2 class="text-green-500">
                     <span class="text-sm 2xl:text-base">$</span>
                     <span class="text-2xl 2xl:text-3xl">{{ book.price }}</span>
                  </h2>
               </div>
               <div class="flex gap-2 mt-5">
                  {% if book.seller.user != user %}
                  <a href="{% url 'Library:purchase' book.id %}" class="flex items-center gap-3 border border-green-500 rounded-md text-green-600 px-5 py-2 text-sm semi-lg:text-base transition-all duration-300 hover:bg-green-500 hover:text-white filter-parent">
                     <img src="{% static 'image/icons/arrow_right.png' %}" class="w-4 h-4 filter-to-green hover-filter-green-to-white transition-all duration-300">
                     <span>Buy Now</span>
                  </a>
                  <button class="flex items-center gap-3 border border-green-500 rounded-md text-green-600 px-5 py-2 text-sm semi-lg:text-base transition-all duration-300 hover:bg-green-500 hover:text-white filter-parent add_to_cart_button" data-book-id="{{ book.id }}">
                     <img src="{% static 'image/icons/cart.png' %}" class="w-4 h-4 filter-to-green hover-filter-green-to-white transition-all duration-300">
                     <span>Add To Cart</span>
                  </button>
                  {% else %}
                  <a href="{% url 'Seller:edit_product' book.id %}" class="flex items-center gap-3 border border-green-500 rounded-md text-green-600 px-5 py-2 text-sm semi-lg:text-base transition-all duration-300 hover:bg-green-500 hover:text-white filter-parent">
                     <img src="{% static 'image/icons/pencil.png' %}" class="w-4 h-4 filter-to-green hover-filter-green-to-white transition-all duration-300">
                     <span>Edit Product</span>
                  </a>
                  {% endif %}
               </div>
            </div>
            <div class="mt-5">
               <h2 class="text-lg 2xl:text-[22px] font-semibold mb-2">Description</h2>
               <p class="text-[15px] semi-lg:text-base 2xl:text-lg">{{ book.desc }}</p>
            </div>
            <div class="mt-5">
               <h2 class="text-lg 2xl:text-[22px] font-semibold mb-2">Book Detail</h2>
               <table class="ml-5 text-sm md:text-base 2xl:text-lg">
                  <tr>
                     <td class="font-semibold">Book Category</td>
                     <td class="w-10 text-center pr-2">:</td>
                     <td>{{ book.category.name }}</td>
                  </tr>
                  {% for detail in details %}
                  <tr>
                     <td class="font-semibold">{{ detail.title }}</td>
                     <td class="w-5 text-center pr-4">:</td>
                     <td>{{ detail.value }}</td>
                  </tr>
                  {% endfor %}
               </table>
            </div>
            <div class="mt-5">
               <h2 class="text-lg 2xl:text-[22px] font-semibold mb-2">Synopsis</h2>
               <p class="text-[15px] semi-lg:text-base 2xl:text-lg">{{ book.synopsis }}</p>
            </div>
         </div>
      </div>
   </div>
</main>

<section class="w-11/12 md:w-5/6 mx-auto md:mt-10">
   <h1 class="text-2xl sm:text-3xl semi-lg:text-4xl 2xl:text-[42px] font-bold mb-7">Other Recommended Books</h1>
   {% include 'library/product_div.html' %}
</section>

<script src="{% static 'js/library.js' %}"></script>
{% endblock %}

templates/library/cart_list_hover.html
{% load static %}
{% load custom_tags %}

{% if cart|length > 0 %}
{% for book in cart %}
<div class="shadow-book-div rounded-md overflow-hidden mb-4">
   <div class="flex gap-2">
      <div class="flex-shrink-0 w-[90px] h-[120px]">
         {% with book|find_main_image as book_main_image %}
         <img src="{{ book_main_image.image.url }}" alt="Image Of '{{ book.name }}' Book"
            class="w-full h-full object-cover rounded-sm">
         {% endwith %}
      </div>
      <div class="p-2">
         <h2 class="transition-all hover:text-red-700">
            <a href="{% url 'Library:book_detail' book.id %}">{{ book.name }}</a>
         </h2>
         <div class="my-1 text-sm italic">
            <p class="my-[2px]">
               <span class="font-bold">Author</span>: {{ book.author }}
            </p>
            <p class="my-[2px]">
               <span class="font-bold">Seller</span>: {{ book.seller.store_name }}
            </p>
         </div>
         <p class="my-[2px] text-green-600">
            <span class="text-xs">$</span><span class="pl-1 font-bold">{{ book.price }}</span>
         </p>
      </div>
   </div>
</div>
{% endfor %}
{% else %}
<div class="mt-2">Your cart is empty. Click the "Add to Cart" to add the book you want to purchase to your cart.</div>
{% endif %}

templates/library/category_based.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}{{ category_name }} Book | VLibrary{% endblock %}

{% block content %}

<main class="w-11/12 md:w-5/6 mx-auto py-28">
   <div class="md:mt-4 mb-4">
      <h1 class="font-bold text-2xl md:text-[27px] xl:text-3xl">Based On Category: {{ category_name }}</h1>
   </div>
   {% if books|length > 0 %}
   {% include 'library/product_div.html' %}
   {% else %}
   <small class="font-semibold text-red-600 text-sm md:text-base">Book with this category are not currently available. Please check again next time.</small>
   {% endif %}
</main>

{% endblock %}

templates/library/contact.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}Contact Us | Give your Feedback or give us some Reports{% endblock %}

{% block content %}
<main class="w-11/12 md:w-5/6 mx-auto pt-24 md:pt-28 pb-20">
   <div class="w-[600px] text-center mx-auto mt-5 mb-7">
      <h1 class="mb-2 text-3xl font-bold">CONTACT US</h1>
      <p class="text-neutral-600 text-sm italic">You can give us feedback or report something on our website. All your feedback and report will help our website very much. So before that, I would like to thank you for your support!</p>
   </div>
   <form method="post" class="w-[500px] mx-auto">
      {% csrf_token %}
      <div class="mb-4">
         <label for="id_name" class="font-semibold">Name:</label>
         {{ form.name }}
         <small>{{ form.name.errors }}</small>
      </div>
      <div class="mb-4">
         <label for="id_email" class="font-semibold">Email:</label>
         {{ form.email }}
         {{ form.email.errors }}
      </div>
      <div class="mb-4">
         <label for="id_message" class="font-semibold">Email:</label>
         {{ form.message }}
         {{ form.message.errors }}
      </div>
      <div class="flex justify-end">
         <button class="border border-red-700 rounded-sm shadow-md px-7 py-2 text-red-700 text-sm transition-all hover:bg-red-500 hover:text-white">Send!</button>
      </div>
   </form>
</main>
{% endblock %}

templates/library/index.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}Search Your Book | VLibrary{% endblock %}

{% block content %}

<main class="w-11/12 md:w-5/6 mx-auto py-28">
   <div class="mt-5 mb-16">
      <form method="get">
         <h1 class="mb-1 font-bold text-2xl md:text-3xl 2xl:text-4xl">Search: </h1>
         <input type="search" class="w-full border border-neutral-600 rounded-sm p-3 outline-none" name="search">
      </form>
      <a href="{% url 'Library:main' %}" class="inline-block border border-red-500 rounded-sm mt-5 px-10 py-2 text-sm text-red-500 transition-all hover:text-white hover:bg-red-500">Reset</a>
   </div>

   {% include 'library/product_div.html' %}
</main>

{% endblock %}

templates/library/product_div.html
{% load static %}
{% load custom_tags %}
<div class="flex items-start gap-[2%] md:gap-[1%] semi-lg:gap-[2%] lg:gap-[1%] xl:gap-[2%] 2xl:gap-[0.5%] flex-wrap">
   {% for book in books %}
   <div
      class="w-[48%] sm:w-[40%] md:w-[32%] lg:w-[24%] xl:w-[23%] 2xl:w-[19.5%] max-w-[240px] lg:max-w-[300px] mb-10 pb-5 shadow-book-div rounded-b-md group">
      <div class="relative w-full aspect-[3_/_4] bg-neutral-300 rounded-t-md overflow-hidden">
         {% with book|find_main_image as book_main_image %}
         <img src="{{ book_main_image.image.url }}" alt="Image Of {{ book.name }}"
         class="w-full h-full object-cover transition-all group-hover:scale-105">
         {% endwith %}
      </div>
      <div class="p-3">
         <h1 class="font-bold mb-2 text-[15px] sm:text-base semi-lg:text-lg hover:text-red-800 transition-all"><a
               href="{% url 'Library:book_detail' book.id %}">{{ book.name }}</a></h1>
         <b class="block mb-2 text-sm text-green-600">$<span class="inline-block text-lg md:text-xl pl-1">{{ book.price }}</span></b>

         {% if user != book.seller.user %}
         {% if book.id|in_cart:request.COOKIES.cart %}
         <button
            class="flex items-center gap-3 bg-green-500 border border-green-500 rounded-md text-white px-5 py-2 text-xs semi-lg:text-base transition-all duration-300 add_to_cart_button"
            data-book-id="{{ book.id }}">
            <img src="{% static 'image/icons/cart.png' %}" class="w-3 h-3 filter-to-white transition-all duration-300">
            <span>Add To Cart</span>
         </button>
         {% else %}
         <button class="flex items-center gap-3 border border-green-500 rounded-md text-green-600 px-5 py-2 text-xs semi-lg:text-base transition-all duration-300 hover:bg-green-500 hover:text-white filter-parent add_to_cart_button" data-book-id="{{ book.id }}">
            <img src="{% static 'image/icons/cart.png' %}" class="w-3 h-3 filter-to-green hover-filter-green-to-white transition-all duration-300">
            <span>Add To Cart</span>
         </button>
         {% endif %}
         {% endif %}
      </div>
   </div>
   {% endfor %}