Library/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from.views import MainIndex, BookDetailPage, PurchasePage, PaymentProcessPage, FeedbackReportPage, add_to_cart, CategoryBasedPage


app_name = 'Library'
urlpatterns = [
   path('', MainIndex.as_view(), name="main"),
   path('book/<pk>', BookDetailPage.as_view(), name="book_detail"),
   path('purchase_book/<book_id>', login_required(PurchasePage.as_view()), name='purchase'),
   path('purchase_book/payment_process/<address>/<shipment_method>/<payment_method>/<book_id>', login_required(PaymentProcessPage.as_view()), name='payment_process'),
   path('feedback-report/contact-us', FeedbackReportPage.as_view(), name='feedback_report'),
   path('book/add-to-cart/<book_id>', add_to_cart, name="add_to_cart"),
   path('category/<category_id>', CategoryBasedPage.as_view(), name="category_based")
]

Seller/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import AddProductPage, OpenSellerAccount, ProductImageUpload, SellerAccountPage, EditSellerAccountPage, EditProductPage, CustomerOrderPage, update_track

app_name = "Seller"
urlpatterns = [
   path('add-product/', login_required(AddProductPage.as_view()), name='add_product'),
   path('edit-product/<pk>', login_required(EditProductPage.as_view()), name='edit_product'),
   path('profile/open-seller-account', login_required(OpenSellerAccount.as_view()), name='open_seller_account'),
   path('product-image-upload/<book_id>', login_required(ProductImageUpload.as_view()), name='upload_image'),
   path('account/<seller_id>', login_required(SellerAccountPage.as_view()), name='account'),
   path('account/edit/<pk>', login_required(EditSellerAccountPage.as_view()), name='edit_seller_account'),
   path('customer_orders/', login_required(CustomerOrderPage.as_view()), name="customer_orders"),
   path('order/udpate_track/<order_id>', login_required(update_track), name="udpate_track"),
]

User/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import WelcomePage, SignUpPage, SignInPage, LogoutPage, ProfilePage, AboutAccountPage, PrivacySecurityPage, SetAddressPage, TransactionHistory, UserCartList

app_name = "User"
urlpatterns = [
   path('', WelcomePage.as_view(), name='welcome'),
   path('sign-up', SignUpPage.as_view(), name='sign_up'),
   path('sign-in', SignInPage.as_view(), name='sign_in'),
   path('user/logout', login_required(LogoutPage.as_view()), name='logout'),
   path('user/profile', login_required(ProfilePage.as_view()), name='profile'),
   path('user/profile/about-account', login_required(AboutAccountPage.as_view()), name='about_account'),
   path('user/profile/privacy-security', login_required(PrivacySecurityPage.as_view()), name='privacy_security'),
   path('user/profile/set-address', login_required(SetAddressPage.as_view()), name='set_address'),
   path('user/history/transaction', login_required(TransactionHistory.as_view()), name='transaction_history'),
   path('user/cart/list', login_required(UserCartList.as_view()), name='cart_list'),
]

Library/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.utils import timezone
from navigation.models import Category
from Seller.models import Seller

# Create your models here.
def minimum_price(value):
   if value > 0:
      return value
   else:
      return ValidationError('Please input price of more than $0')


class Book(models.Model):
   name           = models.CharField(max_length=255, unique=True)
   author         = models.CharField(max_length=150)
   category       = models.ForeignKey(Category, on_delete=models.CASCADE)
   desc           = models.TextField(blank=True)
   synopsis       = models.TextField(blank=True)
   publisher      = models.CharField(max_length=150)
   total_pages    = models.PositiveIntegerField()
   total_chapters = models.PositiveIntegerField()
   publish_year   = models.PositiveIntegerField()
   stock          = models.PositiveIntegerField()
   weight         = models.PositiveIntegerField()
   size           = models.CharField(max_length=100)
   serial_number  = models.CharField(max_length=13)
   price          = models.DecimalField(decimal_places=2, max_digits=10,validators=[minimum_price])
   created_at     = models.DateTimeField(auto_now_add=True)
   seller         = models.ForeignKey(Seller, on_delete=models.CASCADE, blank=True)
   book_activated = models.BooleanField(default=0)

   def __str__(self):
      return f"{self.name} | ${self.price}"


class BookPicture(models.Model):
   image         = models.ImageField(upload_to='book_picture/')
   book          = models.ForeignKey(Book, on_delete=models.CASCADE)
   is_main_image = models.BooleanField(default=False)

   def __str__(self):
      return f"Image for {self.book.name}"


class Transaction(models.Model):
   address         = models.CharField(max_length=150)
   payment_method  = models.CharField(max_length=100)
   shipment_method = models.CharField(max_length=100)
   book            = models.ForeignKey(Book, on_delete=models.CASCADE)
   user            = models.ForeignKey(User, on_delete=models.CASCADE)
   seller          = models.ForeignKey(Seller, on_delete=models.CASCADE)
   created_at      = models.DateTimeField(auto_now_add=True)
   arrival_status  = models.CharField(max_length=50, default="Waiting For Confirmations")
   arrive_date     = models.DateField(blank=True, null=True)
   # Waiting For Confirmations
   # Currently On Shipping
   # Book Arrived!

   
   def __str__(self):
      return f"{self.book.name} | {self.user.username} - {self.address}"

   def save(self, *args, **kwargs):
      if self.arrival_status == 'Book Arrived!':
         self.arrive_date = timezone.now()
      super(Transaction, self).save(*args, **kwargs)


class FeedbackReport(models.Model):
   name    = models.CharField(max_length=150)
   email   = models.EmailField()
   message = models.TextField()

   def __str__(self):
      return "Message from " + self.name


class BookRating(models.Model):
   user   = models.ForeignKey(User, on_delete=models.CASCADE)
   book   = models.ForeignKey(Book, on_delete=models.CASCADE)
   rating = models.FloatField()

   def __str__(self):
      return f"{self.rating} for {self.book.name} | by {self.user.username}"

User/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

# Create your models here.
class UserDetail(models.Model):
   user     = models.OneToOneField(User, primary_key=True, on_delete=models.CASCADE)
   gender   = models.CharField(max_length=10, null=True, blank=True, choices=[
      ('Male', 'Male'),
      ('Female', 'Female'),
   ])
   image    = models.ImageField(upload_to='profile_picture/', default="profile_picture/default.jpg")
   birthday = models.DateField(null=True, blank=True)

   def __str__(self):
      return f"{self.user.username} Detailed Account"

   def save(self, *args, **kwargs):
      super(UserDetail, self).save(*args, **kwargs)
      if self.image:
         image = Image.open(self.image.path)
         image.thumbnail((230, 230))
         image.save(self.image.path)



   

User/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator
from django.contrib.auth import password_validation
from Library.models import Transaction
from .models import UserDetail


class UserRegistrationForm(UserCreationForm):
   email = forms.EmailField(widget=forms.EmailInput(attrs=
            {'class': 'w-full border border-neutral-500 text-[13px] md:text-sm p-[6px] outline-none'}
         ))
   first_name = forms.CharField(max_length=150, widget=forms.TextInput(attrs=
            {'class': 'w-full border border-neutral-500 text-[13px] md:text-sm p-[6px] outline-none'}
         ))
   last_name = forms.CharField(max_length=150, required=False, widget=forms.TextInput(attrs=
            {'class': 'w-full border border-neutral-500 text-[13px] md:text-sm p-[6px] outline-none'}
         ))
   password1 = forms.CharField(max_length=128, widget=forms.PasswordInput(attrs=
            {'class': 'w-full border border-neutral-500 text-[13px] md:text-sm p-[6px] outline-none'}
         ))
   password2 = forms.CharField(max_length=128, widget=forms.PasswordInput(attrs=
            {'class': 'w-full border border-neutral-500 text-[13px] md:text-sm p-[6px] outline-none'}
         ))

   class Meta:
      model = User
      fields = ['username', 'email', 'first_name', 'last_name']
      widgets = { 
         'username': forms.TextInput(attrs=
            {'class': 'w-full border border-neutral-500 text-[13px] md:text-sm p-[6px] outline-none'}
         ),
      }

   def clean_email(self):
      data = self.cleaned_data["email"]
      data_arr = data.split('@')
      valid_email_ext = ['gmail.com', 'email.com', 'yahoo.co.id']
      if data_arr[-1] not in valid_email_ext:
         raise ValidationError('Please use a valid email address!')
      
      return data


class LoginForm(AuthenticationForm):
   username = forms.CharField(max_length=150, widget=forms.TextInput(attrs=
            {'class': 'w-full border border-neutral-500 text-[13px] md:text-sm p-[6px] outline-none'}
         ))
   password = forms.CharField(max_length=150, widget=forms.PasswordInput(attrs=
            {'class': 'w-full border border-neutral-500 text-[13px] md:text-sm p-[6px] outline-none'}
         ))

class EditUserForm(forms.ModelForm):
   class Meta:
      model = User
      fields = ['username', 'first_name', 'last_name', 'email']
      widgets = {
         'username': forms.TextInput(attrs={
            'class': 'block w-full border border-slate-500 rounded-sm mt-1 p-2 text-sm outline-none'
         }),
         'first_name': forms.TextInput(attrs={
            'class': 'block w-full border border-slate-500 rounded-sm mt-1 p-2 text-sm outline-none'
         }),
         'last_name': forms.TextInput(attrs={
            'class': 'block w-full border border-slate-500 rounded-sm mt-1 p-2 text-sm outline-none'
         }),
         'email': forms.EmailInput(attrs={
            'class': 'block w-full border border-slate-500 rounded-sm mt-1 p-2 text-sm outline-none'
         }),
      }

class EditUserDetailForm(forms.ModelForm):
   class Meta:
      model = UserDetail
      exclude = ['user']
      widgets = {
         'gender': forms.HiddenInput(attrs={
            'class': 'block w-full border border-slate-500 rounded-sm mt-1 p-2 text-sm outline-none'
         }),
         'image': forms.FileInput(attrs={
            'class': 'hidden'
         }),
         'birthday': forms.DateInput(attrs={
            'class': 'hidden'
         })
      }


class ChangePasswordForm(forms.Form):
   current_password = forms.CharField(max_length=128, widget=forms.PasswordInput(attrs=
            {'class': 'w-full border border-neutral-500 p-2 mt-1 text-sm outline-none'}
         ))
   new_password = forms.CharField(max_length=128, widget=forms.PasswordInput(attrs=
            {'class': 'w-full border border-neutral-500 p-2 mt-1 text-sm outline-none'}
         ), validators=[MinLengthValidator(8)])
   confirm_password = forms.CharField(max_length=128, widget=forms.PasswordInput(attrs=
            {'class': 'w-full border border-neutral-500 p-2 mt-1 text-sm outline-none'}
         ))

   def clean_new_password(self):
      new_password = self.cleaned_data.get('new_password')
      try: 
         password_validation.validate_password(new_password, self)
      except forms.ValidationError as error:
         self.add_error('new_password', error)

      return new_password

      
class SetAddressForm(forms.ModelForm):
   class Meta:
      model = Transaction
      fields = ['address']
      widgets = {
         'address': forms.TextInput(attrs={
            'class': 'w-full border border-neutral-600 rounded-sm mt-3 p-2 text-[13px] md:text-sm outline-none'
         })
      }

templates/user/about_account.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}About Your Account{% endblock %}

{% block content %}
<main class="w-11/12 md:w-5/6 mx-auto pt-24 md:pt-28 pb-20">
   <h1 class="font-bold text-[32px] md:text-4xl mb-12">Edit Your Account</h1>
   <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <section class="flex gap-10 flex-col md:flex-row semi-lg:gap-16 w-full">
         <div class="flex-shrink-0 pb-10 md:pb-0 lg:px-10">
            <div class="sticky top-28 w-48 h-48 group">
               <img src="{{ user.userdetail.image.url }}" id="profile_picture_preview" class="w-48 h-48 object-cover border-2 border-neutral-800 rounded-full mx-auto md:mx-0 shadow-2xl">
               <div class="absolute inset-0 bg-neutral-800 rounded-full opacity-0 transition-all group-hover:opacity-60"></div>
               <label for="id_image" class="absolute flex items-center justify-center inset-0 text-white opacity-0 select-none transition-all group-hover:opacity-100 cursor-pointer">
                  <p class="absolute font-semibold text-xl text-center">Change Picture</p>
               </label>
               {{ form2.image }}
            </div>
            <small class="block text-red-600 mt-1">{{ form2.image.errors }}</small>
         </div>
         <div class="w-full h-2 md:h-auto md:min-h-full md:w-2 bg-red-500 rounded-full shadow-shining-red flex-shrink-0"></div>
         <div class="w-full max-w-[600px] mx-auto md:mx-0">
            <div class="mb-7">
               <label for="id_username" class="font-semibold">Username: </label>
               {{ form.username }}
               <small class="block text-red-600 mt-1">{{ form.username.errors }}</small>
            </div>
            <div class="mb-7">
               <label for="id_first_name" class="font-semibold">First Name: </label>
               {{ form.first_name }}
               <small class="block text-red-600 mt-1">{{ form.first_name.errors }}</small>
            </div>
            <div class="mb-7">
               <label for="id_last_name" class="font-semibold">Last Name: </label>
               {{ form.last_name }}
               <small class="block text-red-600 mt-1">{{ form.last_name.errors }}</small>
            </div>
            <div class="mb-7">
               <label for="id_email" class="font-semibold">Email: </label>
               {{ form.email }}
               <small class="block text-red-600 mt-1">{{ form.email.errors }}</small>
            </div>
            <div class="mb-7" id="gender_input_wrapper">
               <label for="id_gender" class="font-semibold">Gender: </label>
               {{ form2.gender }}
               <div class="relative">
                  <p class="block w-full border border-slate-500 rounded-sm mt-1 p-2 text-sm cursor-pointer">
                     {% if form2.gender.value %}
                     {{ form2.gender.value }}
                     {% else %}
                     -- Click Here To Select --
                     {% endif %}
                  </p>
                  <div class="hidden absolute top-full -translate-y-4 w-full bg-white border border-slate-400 overflow-auto opacity-0 transition-all duration-300" id="gender_select">
                     <option data-gender-type="Male" class="block w-full p-3 text-sm cursor-pointer hover:bg-slate-200">Male</option>
                     <option data-gender-type="Female" class="block w-full p-3 text-sm cursor-pointer hover:bg-slate-200">Female</option>
                  </div>
               </div>
               <small class="block text-red-600 mt-1">{{ form2.gender.errors }}</small>
            </div>
            <div class="mb-7">
               <label for="id_birthday" class="font-semibold">Birthday: </label>
               {{ form2.birthday }}
               <input type="date" class="block w-full border border-slate-500 rounded-sm mt-1 p-2 text-sm outline-none">
               <small class="block text-red-600 mt-1">{{ form2.birthday.errors }}</small>
            </div>
            <div class="flex justify-end mb-5">
               <button class="border border-red-600 rounded-sm py-2 px-4 text-sm text-red-600 transition-all hover:text-white hover:bg-red-500">Update Account!</button>
            </div>
         </div>
      </section>
   </form>

   <section class="mt-24 text-sm md:text-base">
      <h1 class="font-bold text-[32px] md:text-4xl">About Account</h1>
      <div class="mt-10">
         {% if is_seller %}
         <p class="font-semibold mb-5">Your account is a seller account. Your role is a seller, but you can still buy other seller's product. You can view your channel by clicking the button below(only if your account has been publicized)</p>
         <a href="{% url 'Seller:account' user.id %}" class="border border-green-700 rounded-sm py-2 px-6 text-[13px] md:text-sm text-green-700 transition-all hover:text-white hover:bg-green-700">View Seller Account</a>
         {% else %}
         <p class="font-semibold mb-5">Your account is a user-statused account. Your role is a user for this webiste and as a buyer for book sellers. But you can be a seller by making a channel for yourself. If your role is a seller-statused account, you will still be able to buy books from other store. And surely, your role as a seller is to have product, so you must have at least 1 product before your channel gets publicized. Click this button below to get your seller status and upload your first product.</p>
         <a href="{% url 'Seller:open_seller_account' %}" class="border border-green-700 rounded-sm py-2 px-6 text-[13px] md:text-sm text-green-700 transition-all hover:text-white hover:bg-green-700">Create Seller Account</a>
         {% endif %}
      </div>
      <div class="mt-10">
         <p class="font-semibold mb-5">As a user, we would like to know your feedbacks to help us grow our website. If you have any problem with our website, feel free to click this button below to report your problems. Just a feedback will also help.</p>
         <a href="{% url 'Library:feedback_report' %}" class="border border-neutral-800 rounded-sm py-2 px-6 text-[13px] md:text-sm text-neutral-800 transition-all hover:text-white hover:bg-neutral-800">Report or Feedback</a>
      </div>
      <div class="mt-16">
         <h3 class="mb-3 text-2xl md:text-[26px] text-red-700 font-semibold">Danger Zone</h3>
         <p class="font-semibold mb-5">Please think through your decisions, because after you click this button, all your data will be deleted, your transaction history, your account, everything will be deleted! You won't be able to make a new account using your current email for 7 days.</p>
         <a href="" class="border border-red-700 rounded-sm py-2 px-6 text-[13px] md:text-sm text-red-700 transition-all hover:text-white hover:bg-red-600">Delete This Account</a>
      </div>
   </section>
</main>

<script src="{% static 'js/user.js' %}"></script>
{% endblock %}

templates/user/profile.html
{% extends 'layout.html' %}
{% load static %}
{% load custom_tags %}

{% block title %}Your Profile Page{% endblock %}

{% block content %}

<main class="pt-28 md:pt-32 w-11/12 md:w-5/6 mx-auto">
   <div class="sm:flex gap-8">
      <div class="border-2 border-neutral-800 rounded-full">
         <img src="{{ user.userdetail.image.url }}" class="w-44 h-44 rounded-full object-cover shadow-2xl" alt="{{ user.username }} Profile Picture">
      </div>
      <div class="mt-7 sm:mt-2 px-3 sm:px-0">
         <h1 class="text-3xl md:text-[33px] lg:text-4xl font-bold mb-3">{{ user.get_full_name }}</h1>
         <p class="text-[15px] md:text-base mb-1 italic"><span class="text-gray-700 font-semibold">Username:</span> {{ user.username }}</p>
         <p class="text-[15px] md:text-base mb-1 italic"><span class="text-gray-700 font-semibold">Email Address:</span> {{ user.email }}</p>
      </div>
   </div>
   <div class="rounded-lg w-full md:w-[600px] lg:w-[700px] xl:w-[800px] 2xl:w-[900px] border border-red-300 mt-12 overflow-hidden">
      <div class="bg-red-500 px-5 py-3 text-white text-base md:text-lg font-semibold"><h2>Account Configuration</h2></div>
      {% if is_seller %}
      <a class="flex items-center gap-4 md:gap-5 px-5 md:px-6 py-4 select-none hover:bg-slate-200" href="{% url 'Seller:account' user.id %}">
         <img src="{% static 'image/icons/account.png' %}" class="w-6 h-6 md:w-7 md:h-7 filter-to-gray">
         <div>
            <h2 class="text-[15px] md:text-base 2xl:text-lg font-semibold">View Seller Account</h2>
            <p class="text-sm md:text-[15px] 2xl:text-base text-slate-600 italic">View your seller channel and see all your uploaded product.</p>
         </div>
      </a>
      <a class="flex items-center gap-4 md:gap-5 px-5 md:px-6 py-4 select-none hover:bg-slate-200" href="{% url 'Seller:customer_orders' %}">
         <img src="{% static 'image/icons/order.png' %}" class="w-6 h-6 md:w-7 md:h-7 filter-to-gray">
         <div>
            <h2 class="text-[15px] md:text-base 2xl:text-lg font-semibold">Customer's Order</h2>
            <p class="text-sm md:text-[15px] 2xl:text-base text-slate-600 italic">View your customers order. Give your customers confirmation from new order.</p>
         </div>
      </a>
      {% endif %}
      <a class="flex items-center gap-4 md:gap-5 px-5 md:px-6 py-4 select-none hover:bg-slate-200" href="{% url 'User:set_address' %}">
         <img src="{% static 'image/icons/location.png' %}" class="w-6 h-6 md:w-7 md:h-7 filter-to-gray">
         <div>
            <h2 class="text-[15px] md:text-base 2xl:text-lg font-semibold">Set Adress</h2>
            <p class="text-sm md:text-[15px] 2xl:text-base text-slate-600 italic">Set your address to ease your picking up.</p>
         </div>
      </a>
      <a class="flex items-center gap-4 md:gap-5 px-5 md:px-6 py-4 select-none hover:bg-slate-200" href="{% url 'User:privacy_security' %}">
         <img src="{% static 'image/icons/lock.png' %}" class="w-6 h-6 md:w-7 md:h-7 filter-to-gray">
         <div>
            <h2 class="text-[15px] md:text-base 2xl:text-lg font-semibold">Privacy and Security</h2>
            <p class="text-sm md:text-[15px] 2xl:text-base text-slate-600 italic">Seting your email, password, and other personal information.</p>
         </div>
      </a>
      <a class="flex items-center gap-4 md:gap-5 px-5 md:px-6 py-4 select-none hover:bg-slate-200" href="{% url 'User:about_account' %}">
         <img src="{% static 'image/icons/information.png' %}" class="w-6 h-6 md:w-7 md:h-7 filter-to-gray">
         <div>
            <h2 class="text-[15px] md:text-base 2xl:text-lg font-semibold">About Account</h2>
            <p class="text-sm md:text-[15px] 2xl:text-base text-slate-600 italic">Your current user status. Are you a buyer or a seller?</p>
         </div>
      </a>
   </div>
</main>

<section class="w-11/12 md:w-5/6 mx-auto my-20">
   <h1 class="text-2xl sm:text-[28px] semi-lg:text-[32px] 2xl:text-[39px] font-bold mb-10">On Going Trasactions</h1>
   {% if on_going_transactions|length > 0 %}
   {% for transaction in on_going_transactions %}
   <div class="w-full semi-lg:w-[90%] shadow-book-div rounded-lg mb-10 overflow-hidden">
      <div class="flex gap-3">
         <div
            class="w-[132px] h-[176px] md:w-[150px] md:h-[200px] xl:w-[174px] xl:h-[232px] 2xl:w-[198px] 2xl:h-[264px] flex-shrink-0">
            {% with transaction.book|find_main_image as book_main_image %}
            <img src="{{ book_main_image.image.url }}" alt="Image Of '{{ book.name }}' Book"
               class="w-full h-full object-cover rounded-sm">
            {% endwith %}
         </div>
         <div class="p-4 w-full pr-6">
            <h2 class="semi-lg:text-lg font-bold mb-2">{{ transaction.book.name }}</h2>
            <div class="text-[13px] md:text-[15px] italic">
               <p class="my-1"><span class="font-bold">Address</span>: {{ transaction.address }}</p>
               <p class="my-1"><span class="font-bold">Payment</span>: {{ transaction.payment_method }}</p>
               <p class="my-1"><span class="font-bold">Shipment</span>: {{ transaction.shipment_method }}</p>
               <p class="my-1"><span class="font-bold">Status</span>: {{ order.arrival_status }}</p>
            </div>
         </div>
      </div>
      <div class="p-5 flex justify-end md:hidden">
         <a href="" class="border border-red-600 rounded-sm py-2 px-4 text-sm text-red-600 transition-all hover:text-white hover:bg-red-500">Track Transaction</a>
      </div>
   </div>
   {% endfor %}
   {% else %}
   <div class="pb-16">
      <p>There is no transaction on going for now! <a href="{% url 'Library:main' %}" class="text-red-400">Click here</a> to buy new book.</p>
   </div>
   {% endif %}
</section>

<section class="w-11/12 md:w-5/6 mx-auto md:mt-10">
   <h1 class="text-2xl sm:text-[28px] semi-lg:text-[32px] 2xl:text-[39px] font-bold mb-7">Other Recommended Books</h1>
   {% include 'library/product_div.html' %}
</section>

{% endblock %}

templates/user/sign_up.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}Create Your VLibrary Account{% endblock %}

{% block content %}
<div class="flex">
   <main class="flex justify-center items-center w-full max-h-screen min-h-screen overflow-auto">
      <form
         class="w-11/12 max-w-[500px] md:w-5/6 xl:w-3/4 bg-white rounded-md px-10 md:px-0 py-10 md:py-0 my-10 md:my-16"
         method="post">
         {% csrf_token %}
         <h1 class="text-2xl md:text-[28px] font-bold pb-5">CREATE AN ACCOUNT</h1>
         <div class="w-full h-[6px] bg-red-500 rounded-full shadow-shining-red-small mt-1 mb-10"></div>
         <div class="mb-4">
            <div class="flex gap-[4%]">
               <div class="w-[48%]">
                  <label for="id_first_name" class="text-sm md:text-base font-semibold block">First name:</label>
                  {{ form.first_name }}
               </div>
               <div class="w-[48%]">
                  <label for="id_last_name" class="text-sm md:text-base font-semibold block">Last name:</label>
                  {{ form.last_name }}
               </div>
            </div>
            <small class="text-red-500">{{ form.first_name.errors }}</small>
         </div>
         <div class="mb-4">
            <label for="id_username" class="text-sm md:text-base font-semibold block">Username:</label>
            {{ form.username }}
            <small class="text-red-500">{{ form.username.errors }}</small>
         </div>
         <div class="mb-4">
            <label for="id_email" class="text-sm md:text-base font-semibold block">Email address:</label>
            {{ form.email }}
            <small class="text-red-500">{{ form.email.errors }}</small>
         </div>
         <div class="mb-4">
            <label for="id_password1" class="text-sm md:text-base font-semibold block">Password:</label>
            {{ form.password1 }}
            <small class="text-red-500">{{ form.password1.errors }}</small>
         </div>
         <div class="mb-7">
            <label for="id_password2" class="text-sm md:text-base font-semibold block">Confirm Password:</label>
            {{ form.password2 }}
            <small class="text-red-500">{{ form.password2.errors }}</small>
         </div>
         <button
            class="bg-red-500 rounded-sm px-5 py-2 text-white text-[13px] md:text-sm hover:bg-red-700 transition-all">Create
            Account!</button>
            <p class="mt-4 text-slate-700">Already have an account? <a href="{% url 'User:sign_in' %}" class="text-red-600 hover:underline">Sign In</a></p>
      </form>
   </main>
   <div class="fixed md:static w-full md:w-[45%] lg:w-[55%] 2xl:w-3/5 -z-10 flex-shrink-0">
      <img src="{% static 'image/sign_up_img.jpeg' %}" alt="Library Image"
         class="w-full min-h-screen object-cover object-[70%_30%] lg:object-right brightness-50">
   </div>
</div>
{% endblock %}